 name: FTP Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /home/olaarowo/test.olaarowolo.com
          include: 'public/**/*'  # Optional: Specify files or directories to include
          exclude: 'node_modules/**/*'  # Optional: Specify files or directories to exclude
          
